manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  opw_kinematics_geometric_parameters:
         a1:  0.16
         a2:  -0.15
         b:   0.000
         c1:  0.52
         c2:  0.78
         c3:  0.655
         c4:  0.153
  opw_kinematics_joint_offsets: [0.0, -1.57079632679, 0.0, 0.0, 0.0, 0.0]
  opw_kinematics_joint_sign_corrections: [-1, 1, 1, -1, 1, -1]
